Add target functionality

diff --git a/syncdt b/syncdt
--- a/syncdt
+++ b/syncdt
@@ -6,16 +6,16 @@ function copy {
   msg "Copying files"
   for file in $(cat $sync_file); do
     file=$(echo $file | sed "s@~@$HOME@")
-    target=$PWD$(echo $file | sed "s@$HOME@@")
-    targetdir=${target%/*}
+    local currtarget=$target$(echo $file | sed "s@$HOME@@")
+    local currtargetdir=${target%/*}
 
-    [ ! -d $targetdir ] && mkdir -p $targetdir
+    [ ! -d $currtargetdir ] && mkdir -p $currtargetdir
     if [ -f $file ]; then
-      cp $file $target && echo $file "sync'd to" $target
-      [ $? -ne 0 ] && error "\n$file FAILED to sync"
+      cp $file $currtarget && echo $file "sync'd to" $currtarget
+      [ $? -ne 0 ] && error "$file FAILED to sync"
     else
-      cp $file $targetdir && echo $file "sync'd to" $target
-      [ $? -ne 0 ] && error "\n$file FAILED to sync"
+      cp $file $currtargetdir && echo $file "sync'd to" $currtarget
+      [ $? -ne 0 ] && error "$file FAILED to sync"
     fi
   done
 }
@@ -49,13 +49,14 @@ Usage syncdt [OPTION]..
   -p Push to remote
   -a Add file to sync to the sync.files file
   -f Specify the file with the list of files and directories to be synced
+  -t Specity the target directory
 HERE
 exit 0
 }
 
 function inFile {
-  [ -f $1 ] || return 0
-  for line in $(cat $1 &> /dev/null); do
+  [ ! -f $1 ] && return 0
+  for line in $(cat $1); do
     [ $line = "$2" ] && return 1
   done
 }
@@ -76,10 +77,15 @@ function setfile {
   sync_file=$1
 }
 
+function settarget {
+  target=$1
+}
+
 branch_name="$(git symbolic-ref HEAD 2>/dev/null)" || branch_name="(unnamed branch)"
 branch_name=${branch_name##refs/heads/}
 
 sync_file=sync.files
+target=$PWD
 cmd=none
 eat=false
 
@@ -111,6 +117,9 @@ for arg in $@; do
     -f)
       cmd=setfile
       ;;
+    -t)
+      cmd=settarget
+      ;;
     -h)
       showhelp
       ;;
@@ -123,6 +132,14 @@ done
 for i in ${!funcs[@]}; do
   case ${funcs[$i]} in
     setfile*)
+      calls+=("${funcs[$i]}")
+      break
+      ;;
+  esac
+done
+for i in ${!funcs[@]}; do
+  case ${funcs[$i]} in
+    settarget*)
       calls+=("${funcs[$i]}")
       break
       ;;
@@ -146,7 +163,7 @@ for i in ${!funcs[@]}; do
 done
 
 for i in ${!calls[@]}; do
-  ${calls[$i]}
+   ${calls[$i]}
 done
 
 exit 0
